### ISSUE TITLE
Integrate page with route

### ISSUE THREAD

**Issue by 3mp3ri0r** [Krisma-Perkasa-Engineering/landing-page#23]
Implement route to navigate between pages

- [x] Create model and data for all products and categories and brands - #21 
- [x] Create list of categories and brands - #20 
- [x] Allow user to see back button on non homepage - #22 
- [x] Allow user to see detail product - #27 
- [x] Allow google bot to crawl perfectly on each page - #16 
- [x] Research the best router library to use
- [x] Implement route to navigate between pages
